services:
  #nginx
  web:
    image: nginx:latest
    ports:
      - "9000:80"
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
  #php 
  app:
    build:
      dockerfile: ./php/Dockerfile
    volumes:
      - /var/www/html/vendor
      - ./app:/var/www/html
  #mysql
  db:
    image: mysql:8.0
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - "9010:3306"
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 1974
      MYSQL_USER: ucid
      MYSQL_PASSWORD: 1974
      MYSQL_DATABASE: katzkin
volumes:
  mysqldata: 